//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advobot.Quotes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Groups {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Groups() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advobot.Quotes.Resources.Groups", typeof(Groups).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyQuotes.
        /// </summary>
        internal static string ModifyQuotes {
            get {
                return ResourceManager.GetString("ModifyQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyRuleCategories.
        /// </summary>
        internal static string ModifyRuleCategories {
            get {
                return ResourceManager.GetString("ModifyRuleCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyRules.
        /// </summary>
        internal static string ModifyRules {
            get {
                return ResourceManager.GetString("ModifyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyValue.
        /// </summary>
        internal static string ModifyValue {
            get {
                return ResourceManager.GetString("ModifyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintOutRules.
        /// </summary>
        internal static string PrintOutRules {
            get {
                return ResourceManager.GetString("PrintOutRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemindMe.
        /// </summary>
        internal static string RemindMe {
            get {
                return ResourceManager.GetString("RemindMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SayQuote.
        /// </summary>
        internal static string SayQuote {
            get {
                return ResourceManager.GetString("SayQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap.
        /// </summary>
        internal static string Swap {
            get {
                return ResourceManager.GetString("Swap", resourceCulture);
            }
        }
    }
}
