//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advobot.Quotes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Responses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Responses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advobot.Quotes.Resources.Responses", typeof(Responses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added the quote {0}..
        /// </summary>
        internal static string QuotesAddedQuote {
            get {
                return ResourceManager.GetString("QuotesAddedQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quote {0} has no description..
        /// </summary>
        internal static string QuotesNoDescription {
            get {
                return ResourceManager.GetString("QuotesNoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed the quote {0}..
        /// </summary>
        internal static string QuotesRemovedQuote {
            get {
                return ResourceManager.GetString("QuotesRemovedQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created a reminder for {0} minutes..
        /// </summary>
        internal static string RemindersAddedRemind {
            get {
                return ResourceManager.GetString("RemindersAddedRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added a rule to the category {0}..
        /// </summary>
        internal static string RulesAddedRule {
            get {
                return ResourceManager.GetString("RulesAddedRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created the rule category {0}..
        /// </summary>
        internal static string RulesCreatedCategory {
            get {
                return ResourceManager.GetString("RulesCreatedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted the rule category {0}..
        /// </summary>
        internal static string RulesDeletedCategory {
            get {
                return ResourceManager.GetString("RulesDeletedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid position to insert a rule at..
        /// </summary>
        internal static string RulesInvalidRuleInsert {
            get {
                return ResourceManager.GetString("RulesInvalidRuleInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid position to remove a rule at..
        /// </summary>
        internal static string RulesInvalidRuleRemove {
            get {
                return ResourceManager.GetString("RulesInvalidRuleRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully changed the value of the category {0} to {1}..
        /// </summary>
        internal static string RulesModifiedCategoryValue {
            get {
                return ResourceManager.GetString("RulesModifiedCategoryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully changed the value of the rule {0} to {1}..
        /// </summary>
        internal static string RulesModifiedRuleValue {
            get {
                return ResourceManager.GetString("RulesModifiedRuleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed a rule at #{0} in the category {1}..
        /// </summary>
        internal static string RulesRemovedRule {
            get {
                return ResourceManager.GetString("RulesRemovedRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied rule already exists..
        /// </summary>
        internal static string RulesRuleAlreadyExists {
            get {
                return ResourceManager.GetString("RulesRuleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully swapped the rule categories #{0} ({1} rules) and #{2} ({3} rules)..
        /// </summary>
        internal static string RulesSwappedRuleCategories {
            get {
                return ResourceManager.GetString("RulesSwappedRuleCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully swapped the rules #{0} and #{1] in the category {2}..
        /// </summary>
        internal static string RulesSwappedRules {
            get {
                return ResourceManager.GetString("RulesSwappedRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotes.
        /// </summary>
        internal static string VariableQuotes {
            get {
                return ResourceManager.GetString("VariableQuotes", resourceCulture);
            }
        }
    }
}
