//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advobot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GuildSettingNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuildSettingNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advobot.Resources.GuildSettingNames", typeof(GuildSettingNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned Phrase Names.
        /// </summary>
        internal static string BannedPhraseNames {
            get {
                return ResourceManager.GetString("BannedPhraseNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned Phrase Punishments.
        /// </summary>
        internal static string BannedPhrasePunishments {
            get {
                return ResourceManager.GetString("BannedPhrasePunishments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned Phrase Regex.
        /// </summary>
        internal static string BannedPhraseRegex {
            get {
                return ResourceManager.GetString("BannedPhraseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned Phrase Strings.
        /// </summary>
        internal static string BannedPhraseStrings {
            get {
                return ResourceManager.GetString("BannedPhraseStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Users.
        /// </summary>
        internal static string BotUsers {
            get {
                return ResourceManager.GetString("BotUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Settings.
        /// </summary>
        internal static string CommandSettings {
            get {
                return ResourceManager.GetString("CommandSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye Message.
        /// </summary>
        internal static string GoodbyeMessage {
            get {
                return ResourceManager.GetString("GoodbyeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        internal static string GuildCulture {
            get {
                return ResourceManager.GetString("GuildCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored Command Channels.
        /// </summary>
        internal static string IgnoredCommandChannels {
            get {
                return ResourceManager.GetString("IgnoredCommandChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored Log Channels.
        /// </summary>
        internal static string IgnoredLogChannels {
            get {
                return ResourceManager.GetString("IgnoredLogChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored Xp Channels.
        /// </summary>
        internal static string IgnoredXpChannels {
            get {
                return ResourceManager.GetString("IgnoredXpChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Log.
        /// </summary>
        internal static string ImageLog {
            get {
                return ResourceManager.GetString("ImageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Only Channels.
        /// </summary>
        internal static string ImageOnlyChannels {
            get {
                return ResourceManager.GetString("ImageOnlyChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Actions.
        /// </summary>
        internal static string LogActions {
            get {
                return ResourceManager.GetString("LogActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Log.
        /// </summary>
        internal static string ModLog {
            get {
                return ResourceManager.GetString("ModLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute Role.
        /// </summary>
        internal static string MuteRole {
            get {
                return ResourceManager.GetString("MuteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Verbose Errors.
        /// </summary>
        internal static string NonVerboseErrors {
            get {
                return ResourceManager.GetString("NonVerboseErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent Roles.
        /// </summary>
        internal static string PersistentRoles {
            get {
                return ResourceManager.GetString("PersistentRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotes.
        /// </summary>
        internal static string Quotes {
            get {
                return ResourceManager.GetString("Quotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raid Prevention.
        /// </summary>
        internal static string RaidPrevention {
            get {
                return ResourceManager.GetString("RaidPrevention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        internal static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Assignable Groups.
        /// </summary>
        internal static string SelfAssignableGroups {
            get {
                return ResourceManager.GetString("SelfAssignableGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Log.
        /// </summary>
        internal static string ServerLog {
            get {
                return ResourceManager.GetString("ServerLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam Prevention.
        /// </summary>
        internal static string SpamPrevention {
            get {
                return ResourceManager.GetString("SpamPrevention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Message.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
