//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advobot.Settings.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Summaries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Summaries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advobot.Settings.Resources.Summaries", typeof(Summaries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives or takes a role depending on if the user already has it. Removes all other roles in the same group unless the group is 0..
        /// </summary>
        internal static string AssignSelfRole {
            get {
                return ResourceManager.GetString("AssignSelfRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the groups and roles which can be self assigned..
        /// </summary>
        internal static string DisplaySelfRoles {
            get {
                return ResourceManager.GetString("DisplaySelfRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns commands on and off..
        /// </summary>
        internal static string ModifyCommands {
            get {
                return ResourceManager.GetString("ModifyCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bot will ignore commands said on these channels. If a command is input then the bot will instead ignore only that command on the given channel..
        /// </summary>
        internal static string ModifyIgnoredCommandChannels {
            get {
                return ResourceManager.GetString("ModifyIgnoredCommandChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds the given text to a list that can be called through the SayQuote command.
        /// </summary>
        internal static string ModifyQuotes {
            get {
                return ResourceManager.GetString("ModifyQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the categories which contain rules..
        /// </summary>
        internal static string ModifyRuleCategories {
            get {
                return ResourceManager.GetString("ModifyRuleCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the rules which are saved in guild settings..
        /// </summary>
        internal static string ModifyRules {
            get {
                return ResourceManager.GetString("ModifyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies self assignable roles..
        /// </summary>
        internal static string ModifySelfRoles {
            get {
                return ResourceManager.GetString("ModifySelfRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the rules with user specified formatting..
        /// </summary>
        internal static string PrintOutRules {
            get {
                return ResourceManager.GetString("PrintOutRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets settings back to their default values..
        /// </summary>
        internal static string ResetGuildSettings {
            get {
                return ResourceManager.GetString("ResetGuildSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the content for the given quote..
        /// </summary>
        internal static string SayQuote {
            get {
                return ResourceManager.GetString("SayQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows information about the bot settings..
        /// </summary>
        internal static string ShowBotSettings {
            get {
                return ResourceManager.GetString("ShowBotSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows information about guild settings..
        /// </summary>
        internal static string ShowGuildSettings {
            get {
                return ResourceManager.GetString("ShowGuildSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends the given guild notification in order to test it..
        /// </summary>
        internal static string TestGuildNotifs {
            get {
                return ResourceManager.GetString("TestGuildNotifs", resourceCulture);
            }
        }
    }
}
