//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advobot.AutoMod.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Responses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Responses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advobot.AutoMod.Resources.Responses", typeof(Responses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already a banned {1}..
        /// </summary>
        internal static string BannedPhraseAlreadyExists {
            get {
                return ResourceManager.GetString("BannedPhraseAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully changed the punishment of the banned {0} {1} to {2}..
        /// </summary>
        internal static string BannedPhraseChangedPunishment {
            get {
                return ResourceManager.GetString("BannedPhraseChangedPunishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully {0} the banned {1} {2}..
        /// </summary>
        internal static string BannedPhraseModified {
            get {
                return ResourceManager.GetString("BannedPhraseModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not already a banned {0}..
        /// </summary>
        internal static string BannedPhraseNotExisting {
            get {
                return ResourceManager.GetString("BannedPhraseNotExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to banned {0}.
        /// </summary>
        internal static string BannedPhraseType {
            get {
                return ResourceManager.GetString("BannedPhraseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added.
        /// </summary>
        internal static string BannedPhraseVariableAdded {
            get {
                return ResourceManager.GetString("BannedPhraseVariableAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string BannedPhraseVariableName {
            get {
                return ResourceManager.GetString("BannedPhraseVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None..
        /// </summary>
        internal static string BannedPhraseVariableNone {
            get {
                return ResourceManager.GetString("BannedPhraseVariableNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regex.
        /// </summary>
        internal static string BannedPhraseVariableRegex {
            get {
                return ResourceManager.GetString("BannedPhraseVariableRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removed.
        /// </summary>
        internal static string BannedPhraseVariableRemoved {
            get {
                return ResourceManager.GetString("BannedPhraseVariableRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.
        /// </summary>
        internal static string BannedPhraseVariableString {
            get {
                return ResourceManager.GetString("BannedPhraseVariableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} prevention is already {2}..
        /// </summary>
        internal static string SpamPreventionAlreadyToggled {
            get {
                return ResourceManager.GetString("SpamPreventionAlreadyToggled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created {0} {1} prevention..
        /// </summary>
        internal static string SpamPreventionCreated {
            get {
                return ResourceManager.GetString("SpamPreventionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find a {0} {1} prevention..
        /// </summary>
        internal static string SpamPreventionNotFound {
            get {
                return ResourceManager.GetString("SpamPreventionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully {0} the {1} {2} prevention..
        /// </summary>
        internal static string SpamPreventionToggled {
            get {
                return ResourceManager.GetString("SpamPreventionToggled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled.
        /// </summary>
        internal static string SpamPreventionVariableDisabled {
            get {
                return ResourceManager.GetString("SpamPreventionVariableDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enabled.
        /// </summary>
        internal static string SpamPreventionVariableEnabled {
            get {
                return ResourceManager.GetString("SpamPreventionVariableEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raid.
        /// </summary>
        internal static string SpamPreventionVariableRaid {
            get {
                return ResourceManager.GetString("SpamPreventionVariableRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spam.
        /// </summary>
        internal static string SpamPreventionVariableSpam {
            get {
                return ResourceManager.GetString("SpamPreventionVariableSpam", resourceCulture);
            }
        }
    }
}
