//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advobot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advobot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Global_Settings
        ///globalbotowner:ON
        ///globalsavepath:ON
        ///globalprefix:ON
        ///globalsettings:ON
        ///boticon:ON
        ///botgame:ON
        ///botstream:ON
        ///botname:ON
        ///disconnect:ON
        ///restart:ON
        ///listguilds:ON
        ///
        ///@Guild_Settings
        ///guildleave:ON
        ///guildprefix:OFF
        ///guildsettings:ON
        ///comconfigmodify:ON
        ///comconfigcurrent:ON
        ///comconfigtoggle:ON
        ///botusersmodify:OFF
        ///botuserscurrent:OFF
        ///remindmodify:OFF
        ///remind:OFF
        ///
        ///@Logs
        ///botchannel:ON
        ///logserver:OFF
        ///logmod:OFF
        ///logignore:OFF
        ///logactions:OFF
        ///
        ///@Ban_Phrases
        ///banphrasesmodify:OFF
        ///banphra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultCommandPreferences {
            get {
                return ResourceManager.GetString("DefaultCommandPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Graphic_Design {
            get {
                object obj = ResourceManager.GetObject("Graphic_Design", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
