//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advobot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Groups {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Groups() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advobot.Resources.Groups", typeof(Groups).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animated.
        /// </summary>
        public static string Animated {
            get {
                return ResourceManager.GetString("Animated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssignSelfRole.
        /// </summary>
        public static string AssignSelfRole {
            get {
                return ResourceManager.GetString("AssignSelfRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban.
        /// </summary>
        public static string Ban {
            get {
                return ResourceManager.GetString("Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot.
        /// </summary>
        public static string Bot {
            get {
                return ResourceManager.GetString("Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bump.
        /// </summary>
        public static string Bump {
            get {
                return ResourceManager.GetString("Bump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangePunishment.
        /// </summary>
        public static string ChangePunishment {
            get {
                return ResourceManager.GetString("ChangePunishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearChannelPerms.
        /// </summary>
        public static string ClearChannelPerms {
            get {
                return ResourceManager.GetString("ClearChannelPerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearGroup.
        /// </summary>
        public static string ClearGroup {
            get {
                return ResourceManager.GetString("ClearGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearNickname.
        /// </summary>
        public static string ClearNickname {
            get {
                return ResourceManager.GetString("ClearNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearRolePerms.
        /// </summary>
        public static string ClearRolePerms {
            get {
                return ResourceManager.GetString("ClearRolePerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyChannelPerms.
        /// </summary>
        public static string CopyChannelPerms {
            get {
                return ResourceManager.GetString("CopyChannelPerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyRolePerms.
        /// </summary>
        public static string CopyRolePerms {
            get {
                return ResourceManager.GetString("CopyRolePerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateChannel.
        /// </summary>
        public static string CreateChannel {
            get {
                return ResourceManager.GetString("CreateChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateEmote.
        /// </summary>
        public static string CreateEmote {
            get {
                return ResourceManager.GetString("CreateEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateGuild.
        /// </summary>
        public static string CreateGuild {
            get {
                return ResourceManager.GetString("CreateGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateInvite.
        /// </summary>
        public static string CreateInvite {
            get {
                return ResourceManager.GetString("CreateInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateRole.
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateRoleRestrictedChannel.
        /// </summary>
        public static string CreateRoleRestrictedChannel {
            get {
                return ResourceManager.GetString("CreateRoleRestrictedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateWebhook.
        /// </summary>
        public static string CreateWebhook {
            get {
                return ResourceManager.GetString("CreateWebhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deafen.
        /// </summary>
        public static string Deafen {
            get {
                return ResourceManager.GetString("Deafen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteChannel.
        /// </summary>
        public static string DeleteChannel {
            get {
                return ResourceManager.GetString("DeleteChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteEmote.
        /// </summary>
        public static string DeleteEmote {
            get {
                return ResourceManager.GetString("DeleteEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteGuild.
        /// </summary>
        public static string DeleteGuild {
            get {
                return ResourceManager.GetString("DeleteGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteInvite.
        /// </summary>
        public static string DeleteInvite {
            get {
                return ResourceManager.GetString("DeleteInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteMultipleInvites.
        /// </summary>
        public static string DeleteMultipleInvites {
            get {
                return ResourceManager.GetString("DeleteMultipleInvites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteRole.
        /// </summary>
        public static string DeleteRole {
            get {
                return ResourceManager.GetString("DeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteWebhook.
        /// </summary>
        public static string DeleteWebhook {
            get {
                return ResourceManager.GetString("DeleteWebhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisconnectBot.
        /// </summary>
        public static string DisconnectBot {
            get {
                return ResourceManager.GetString("DisconnectBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayBannedPhrases.
        /// </summary>
        public static string DisplayBannedPhrases {
            get {
                return ResourceManager.GetString("DisplayBannedPhrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayChannelPerms.
        /// </summary>
        public static string DisplayChannelPerms {
            get {
                return ResourceManager.GetString("DisplayChannelPerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayChannelPosition.
        /// </summary>
        public static string DisplayChannelPosition {
            get {
                return ResourceManager.GetString("DisplayChannelPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayCurrentBanList.
        /// </summary>
        public static string DisplayCurrentBanList {
            get {
                return ResourceManager.GetString("DisplayCurrentBanList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayEmotes.
        /// </summary>
        public static string DisplayEmotes {
            get {
                return ResourceManager.GetString("DisplayEmotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayInvites.
        /// </summary>
        public static string DisplayInvites {
            get {
                return ResourceManager.GetString("DisplayInvites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayPersistentRoles.
        /// </summary>
        public static string DisplayPersistentRoles {
            get {
                return ResourceManager.GetString("DisplayPersistentRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayRolePerms.
        /// </summary>
        public static string DisplayRolePerms {
            get {
                return ResourceManager.GetString("DisplayRolePerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayRolePositions.
        /// </summary>
        public static string DisplayRolePositions {
            get {
                return ResourceManager.GetString("DisplayRolePositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplaySelfRoles.
        /// </summary>
        public static string DisplaySelfRoles {
            get {
                return ResourceManager.GetString("DisplaySelfRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayWebhooks.
        /// </summary>
        public static string DisplayWebhooks {
            get {
                return ResourceManager.GetString("DisplayWebhooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed.
        /// </summary>
        public static string Embed {
            get {
                return ResourceManager.GetString("Embed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emote.
        /// </summary>
        public static string Emote {
            get {
                return ResourceManager.GetString("Emote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fake.
        /// </summary>
        public static string Fake {
            get {
                return ResourceManager.GetString("Fake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForAllWithRole.
        /// </summary>
        public static string ForAllWithRole {
            get {
                return ResourceManager.GetString("ForAllWithRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gacha.
        /// </summary>
        public static string Gacha {
            get {
                return ResourceManager.GetString("Gacha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get.
        /// </summary>
        public static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetBanReason.
        /// </summary>
        public static string GetBanReason {
            get {
                return ResourceManager.GetString("GetBanReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetEnumNames.
        /// </summary>
        public static string GetEnumNames {
            get {
                return ResourceManager.GetString("GetEnumNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetGuilds.
        /// </summary>
        public static string GetGuilds {
            get {
                return ResourceManager.GetString("GetGuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetInfo.
        /// </summary>
        public static string GetInfo {
            get {
                return ResourceManager.GetString("GetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetLogCounters.
        /// </summary>
        public static string GetLogCounters {
            get {
                return ResourceManager.GetString("GetLogCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetMessages.
        /// </summary>
        public static string GetMessages {
            get {
                return ResourceManager.GetString("GetMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPermNamesFromValue.
        /// </summary>
        public static string GetPermNamesFromValue {
            get {
                return ResourceManager.GetString("GetPermNamesFromValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUserAvatar.
        /// </summary>
        public static string GetUserAvatar {
            get {
                return ResourceManager.GetString("GetUserAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUserJoinedAt.
        /// </summary>
        public static string GetUserJoinedAt {
            get {
                return ResourceManager.GetString("GetUserJoinedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUserJoinList.
        /// </summary>
        public static string GetUserJoinList {
            get {
                return ResourceManager.GetString("GetUserJoinList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUsersWithReason.
        /// </summary>
        public static string GetUsersWithReason {
            get {
                return ResourceManager.GetString("GetUsersWithReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give.
        /// </summary>
        public static string Give {
            get {
                return ResourceManager.GetString("Give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiveNickname.
        /// </summary>
        public static string GiveNickname {
            get {
                return ResourceManager.GetString("GiveNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiveRole.
        /// </summary>
        public static string GiveRole {
            get {
                return ResourceManager.GetString("GiveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        public static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye.
        /// </summary>
        public static string Goodbye {
            get {
                return ResourceManager.GetString("Goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild.
        /// </summary>
        public static string Guild {
            get {
                return ResourceManager.GetString("Guild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GuildUsers.
        /// </summary>
        public static string GuildUsers {
            get {
                return ResourceManager.GetString("GuildUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harem.
        /// </summary>
        public static string Harem {
            get {
                return ResourceManager.GetString("Harem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        public static string Invite {
            get {
                return ResourceManager.GetString("Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invites.
        /// </summary>
        public static string Invites {
            get {
                return ResourceManager.GetString("Invites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json.
        /// </summary>
        public static string Json {
            get {
                return ResourceManager.GetString("Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick.
        /// </summary>
        public static string Kick {
            get {
                return ResourceManager.GetString("Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeaveGuild.
        /// </summary>
        public static string LeaveGuild {
            get {
                return ResourceManager.GetString("LeaveGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        public static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MakeAnEmbed.
        /// </summary>
        public static string MakeAnEmbed {
            get {
                return ResourceManager.GetString("MakeAnEmbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed.
        /// </summary>
        public static string Managed {
            get {
                return ResourceManager.GetString("Managed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many.
        /// </summary>
        public static string Many {
            get {
                return ResourceManager.GetString("Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBoost.
        /// </summary>
        public static string MessageBoost {
            get {
                return ResourceManager.GetString("MessageBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBotOwner.
        /// </summary>
        public static string MessageBotOwner {
            get {
                return ResourceManager.GetString("MessageBotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageRole.
        /// </summary>
        public static string MessageRole {
            get {
                return ResourceManager.GetString("MessageRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageWelcome.
        /// </summary>
        public static string MessageWelcome {
            get {
                return ResourceManager.GetString("MessageWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyActions.
        /// </summary>
        public static string ModifyActions {
            get {
                return ResourceManager.GetString("ModifyActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyBannedNames.
        /// </summary>
        public static string ModifyBannedNames {
            get {
                return ResourceManager.GetString("ModifyBannedNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyBannedRegex.
        /// </summary>
        public static string ModifyBannedRegex {
            get {
                return ResourceManager.GetString("ModifyBannedRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyBannedStrings.
        /// </summary>
        public static string ModifyBannedStrings {
            get {
                return ResourceManager.GetString("ModifyBannedStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyBotIcon.
        /// </summary>
        public static string ModifyBotIcon {
            get {
                return ResourceManager.GetString("ModifyBotIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyBotName.
        /// </summary>
        public static string ModifyBotName {
            get {
                return ResourceManager.GetString("ModifyBotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyChannelBitRate.
        /// </summary>
        public static string ModifyChannelBitRate {
            get {
                return ResourceManager.GetString("ModifyChannelBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyChannelLimit.
        /// </summary>
        public static string ModifyChannelLimit {
            get {
                return ResourceManager.GetString("ModifyChannelLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyChannelName.
        /// </summary>
        public static string ModifyChannelName {
            get {
                return ResourceManager.GetString("ModifyChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyChannelNsfw.
        /// </summary>
        public static string ModifyChannelNsfw {
            get {
                return ResourceManager.GetString("ModifyChannelNsfw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyChannelPerms.
        /// </summary>
        public static string ModifyChannelPerms {
            get {
                return ResourceManager.GetString("ModifyChannelPerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyChannelPosition.
        /// </summary>
        public static string ModifyChannelPosition {
            get {
                return ResourceManager.GetString("ModifyChannelPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyChannelTopic.
        /// </summary>
        public static string ModifyChannelTopic {
            get {
                return ResourceManager.GetString("ModifyChannelTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyCommands.
        /// </summary>
        public static string ModifyCommands {
            get {
                return ResourceManager.GetString("ModifyCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyEmoteName.
        /// </summary>
        public static string ModifyEmoteName {
            get {
                return ResourceManager.GetString("ModifyEmoteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyEmoteRoles.
        /// </summary>
        public static string ModifyEmoteRoles {
            get {
                return ResourceManager.GetString("ModifyEmoteRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyGoodbyeMessage.
        /// </summary>
        public static string ModifyGoodbyeMessage {
            get {
                return ResourceManager.GetString("ModifyGoodbyeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyGuildAfkChannel.
        /// </summary>
        public static string ModifyGuildAfkChannel {
            get {
                return ResourceManager.GetString("ModifyGuildAfkChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyGuildAfkTimer.
        /// </summary>
        public static string ModifyGuildAfkTimer {
            get {
                return ResourceManager.GetString("ModifyGuildAfkTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyGuildExplicitContentFilter.
        /// </summary>
        public static string ModifyGuildExplicitContentFilter {
            get {
                return ResourceManager.GetString("ModifyGuildExplicitContentFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyGuildIcon.
        /// </summary>
        public static string ModifyGuildIcon {
            get {
                return ResourceManager.GetString("ModifyGuildIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyGuildMsgNotif.
        /// </summary>
        public static string ModifyGuildMsgNotif {
            get {
                return ResourceManager.GetString("ModifyGuildMsgNotif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyGuildName.
        /// </summary>
        public static string ModifyGuildName {
            get {
                return ResourceManager.GetString("ModifyGuildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyGuildRegion.
        /// </summary>
        public static string ModifyGuildRegion {
            get {
                return ResourceManager.GetString("ModifyGuildRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyGuildSplash.
        /// </summary>
        public static string ModifyGuildSplash {
            get {
                return ResourceManager.GetString("ModifyGuildSplash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyGuildSystemChannel.
        /// </summary>
        public static string ModifyGuildSystemChannel {
            get {
                return ResourceManager.GetString("ModifyGuildSystemChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyGuildVerif.
        /// </summary>
        public static string ModifyGuildVerif {
            get {
                return ResourceManager.GetString("ModifyGuildVerif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyIgnoredChannels.
        /// </summary>
        public static string ModifyIgnoredChannels {
            get {
                return ResourceManager.GetString("ModifyIgnoredChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyIgnoredCommandChannels.
        /// </summary>
        public static string ModifyIgnoredCommandChannels {
            get {
                return ResourceManager.GetString("ModifyIgnoredCommandChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyImageLog.
        /// </summary>
        public static string ModifyImageLog {
            get {
                return ResourceManager.GetString("ModifyImageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyModLog.
        /// </summary>
        public static string ModifyModLog {
            get {
                return ResourceManager.GetString("ModifyModLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyName.
        /// </summary>
        public static string ModifyName {
            get {
                return ResourceManager.GetString("ModifyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyNickName.
        /// </summary>
        public static string ModifyNickName {
            get {
                return ResourceManager.GetString("ModifyNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyPersistentRoles.
        /// </summary>
        public static string ModifyPersistentRoles {
            get {
                return ResourceManager.GetString("ModifyPersistentRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyPunishments.
        /// </summary>
        public static string ModifyPunishments {
            get {
                return ResourceManager.GetString("ModifyPunishments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyQuotes.
        /// </summary>
        public static string ModifyQuotes {
            get {
                return ResourceManager.GetString("ModifyQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyRoleColor.
        /// </summary>
        public static string ModifyRoleColor {
            get {
                return ResourceManager.GetString("ModifyRoleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyRoleHoist.
        /// </summary>
        public static string ModifyRoleHoist {
            get {
                return ResourceManager.GetString("ModifyRoleHoist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyRoleMentionability.
        /// </summary>
        public static string ModifyRoleMentionability {
            get {
                return ResourceManager.GetString("ModifyRoleMentionability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyRoleName.
        /// </summary>
        public static string ModifyRoleName {
            get {
                return ResourceManager.GetString("ModifyRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyRolePerms.
        /// </summary>
        public static string ModifyRolePerms {
            get {
                return ResourceManager.GetString("ModifyRolePerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyRolePosition.
        /// </summary>
        public static string ModifyRolePosition {
            get {
                return ResourceManager.GetString("ModifyRolePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyRuleCategories.
        /// </summary>
        public static string ModifyRuleCategories {
            get {
                return ResourceManager.GetString("ModifyRuleCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyRules.
        /// </summary>
        public static string ModifyRules {
            get {
                return ResourceManager.GetString("ModifyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifySelfRoles.
        /// </summary>
        public static string ModifySelfRoles {
            get {
                return ResourceManager.GetString("ModifySelfRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyServerLog.
        /// </summary>
        public static string ModifyServerLog {
            get {
                return ResourceManager.GetString("ModifyServerLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyValue.
        /// </summary>
        public static string ModifyValue {
            get {
                return ResourceManager.GetString("ModifyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyWebhookChannel.
        /// </summary>
        public static string ModifyWebhookChannel {
            get {
                return ResourceManager.GetString("ModifyWebhookChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyWebhookIcon.
        /// </summary>
        public static string ModifyWebhookIcon {
            get {
                return ResourceManager.GetString("ModifyWebhookIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyWebhookName.
        /// </summary>
        public static string ModifyWebhookName {
            get {
                return ResourceManager.GetString("ModifyWebhookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyWelcomeMessage.
        /// </summary>
        public static string ModifyWelcomeMessage {
            get {
                return ResourceManager.GetString("ModifyWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoveUser.
        /// </summary>
        public static string MoveUser {
            get {
                return ResourceManager.GetString("MoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoveUsers.
        /// </summary>
        public static string MoveUsers {
            get {
                return ResourceManager.GetString("MoveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string Mute {
            get {
                return ResourceManager.GetString("Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        public static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreventRaid.
        /// </summary>
        public static string PreventRaid {
            get {
                return ResourceManager.GetString("PreventRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreventSpam.
        /// </summary>
        public static string PreventSpam {
            get {
                return ResourceManager.GetString("PreventSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintOutRules.
        /// </summary>
        public static string PrintOutRules {
            get {
                return ResourceManager.GetString("PrintOutRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PruneUsers.
        /// </summary>
        public static string PruneUsers {
            get {
                return ResourceManager.GetString("PruneUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real.
        /// </summary>
        public static string Real {
            get {
                return ResourceManager.GetString("Real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex.
        /// </summary>
        public static string Regex {
            get {
                return ResourceManager.GetString("Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind.
        /// </summary>
        public static string Remind {
            get {
                return ResourceManager.GetString("Remind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemindMe.
        /// </summary>
        public static string RemindMe {
            get {
                return ResourceManager.GetString("RemindMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveAll.
        /// </summary>
        public static string RemoveAll {
            get {
                return ResourceManager.GetString("RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveAllNickNames.
        /// </summary>
        public static string RemoveAllNickNames {
            get {
                return ResourceManager.GetString("RemoveAllNickNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveMessages.
        /// </summary>
        public static string RemoveMessages {
            get {
                return ResourceManager.GetString("RemoveMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReplaceByUtf16.
        /// </summary>
        public static string ReplaceByUtf16 {
            get {
                return ResourceManager.GetString("ReplaceByUtf16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReplaceWordsInNames.
        /// </summary>
        public static string ReplaceWordsInNames {
            get {
                return ResourceManager.GetString("ReplaceWordsInNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetGuildSettings.
        /// </summary>
        public static string ResetGuildSettings {
            get {
                return ResourceManager.GetString("ResetGuildSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestartBot.
        /// </summary>
        public static string RestartBot {
            get {
                return ResourceManager.GetString("RestartBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll.
        /// </summary>
        public static string Roll {
            get {
                return ResourceManager.GetString("Roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SayQuote.
        /// </summary>
        public static string SayQuote {
            get {
                return ResourceManager.GetString("SayQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shards.
        /// </summary>
        public static string Shards {
            get {
                return ResourceManager.GetString("Shards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowBotSettings.
        /// </summary>
        public static string ShowBotSettings {
            get {
                return ResourceManager.GetString("ShowBotSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowGuildSettings.
        /// </summary>
        public static string ShowGuildSettings {
            get {
                return ResourceManager.GetString("ShowGuildSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoftBan.
        /// </summary>
        public static string SoftBan {
            get {
                return ResourceManager.GetString("SoftBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoftDeleteChannel.
        /// </summary>
        public static string SoftDeleteChannel {
            get {
                return ResourceManager.GetString("SoftDeleteChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoftDeleteRole.
        /// </summary>
        public static string SoftDeleteRole {
            get {
                return ResourceManager.GetString("SoftDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpeakThroughWebhook.
        /// </summary>
        public static string SpeakThroughWebhook {
            get {
                return ResourceManager.GetString("SpeakThroughWebhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strings.
        /// </summary>
        public static string Strings {
            get {
                return ResourceManager.GetString("Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap.
        /// </summary>
        public static string Swap {
            get {
                return ResourceManager.GetString("Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwapGuildOwner.
        /// </summary>
        public static string SwapGuildOwner {
            get {
                return ResourceManager.GetString("SwapGuildOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TakeRole.
        /// </summary>
        public static string TakeRole {
            get {
                return ResourceManager.GetString("TakeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestGuildNotifs.
        /// </summary>
        public static string TestGuildNotifs {
            get {
                return ResourceManager.GetString("TestGuildNotifs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade.
        /// </summary>
        public static string Trade {
            get {
                return ResourceManager.GetString("Trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unban.
        /// </summary>
        public static string Unban {
            get {
                return ResourceManager.GetString("Unban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice.
        /// </summary>
        public static string Voice {
            get {
                return ResourceManager.GetString("Voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoiceMute.
        /// </summary>
        public static string VoiceMute {
            get {
                return ResourceManager.GetString("VoiceMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhook.
        /// </summary>
        public static string Webhook {
            get {
                return ResourceManager.GetString("Webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
