//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advobot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Responses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Responses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advobot.Resources.Responses", typeof(Responses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added the banned {0} {1}..
        /// </summary>
        public static string BannedPhraseAdded {
            get {
                return ResourceManager.GetString("BannedPhraseAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already a banned {1}..
        /// </summary>
        public static string BannedPhraseAlreadyExists {
            get {
                return ResourceManager.GetString("BannedPhraseAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully changed the punishment of the banned {0} {1} to {2}..
        /// </summary>
        public static string BannedPhraseChangedPunishment {
            get {
                return ResourceManager.GetString("BannedPhraseChangedPunishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not already a banned {0}..
        /// </summary>
        public static string BannedPhraseNotExisting {
            get {
                return ResourceManager.GetString("BannedPhraseNotExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed the banned {0} {1}..
        /// </summary>
        public static string BannedPhraseRemoved {
            get {
                return ResourceManager.GetString("BannedPhraseRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to banned {0}.
        /// </summary>
        public static string BannedPhraseType {
            get {
                return ResourceManager.GetString("BannedPhraseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully cleared {0} overwrites from {1}..
        /// </summary>
        public static string ChannelsClearedOverwrites {
            get {
                return ResourceManager.GetString("ChannelsClearedOverwrites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully copied {0} from {1} to {2}..
        /// </summary>
        public static string ChannelsCopiedOverwrite {
            get {
                return ResourceManager.GetString("ChannelsCopiedOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created {0} and restricted access to people with {1}..
        /// </summary>
        public static string ChannelsCreatededRoleRestrictedChannel {
            get {
                return ResourceManager.GetString("ChannelsCreatededRoleRestrictedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy channel permissions because {0} and {1} are not the same type..
        /// </summary>
        public static string ChannelsFailedPermissionCopy {
            get {
                return ResourceManager.GetString("ChannelsFailedPermissionCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the bitrate for {0} to {1}kbps..
        /// </summary>
        public static string ChannelsModifiedBitrate {
            get {
                return ResourceManager.GetString("ChannelsModifiedBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the user limit for {0} to {1}..
        /// </summary>
        public static string ChannelsModifiedLimit {
            get {
                return ResourceManager.GetString("ChannelsModifiedLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the NSFW status for {0} to {1}..
        /// </summary>
        public static string ChannelsModifiedNsfw {
            get {
                return ResourceManager.GetString("ChannelsModifiedNsfw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully allowed {0} for {1} on {2}..
        /// </summary>
        public static string ChannelsModifiedOverwriteAllow {
            get {
                return ResourceManager.GetString("ChannelsModifiedOverwriteAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully denied {0} for {1} on {2}..
        /// </summary>
        public static string ChannelsModifiedOverwriteDeny {
            get {
                return ResourceManager.GetString("ChannelsModifiedOverwriteDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully inherited {0} for {1} on {2}..
        /// </summary>
        public static string ChannelsModifiedOverwriteInherit {
            get {
                return ResourceManager.GetString("ChannelsModifiedOverwriteInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the topic for {0} to {1}..
        /// </summary>
        public static string ChannelsModifiedTopic {
            get {
                return ResourceManager.GetString("ChannelsModifiedTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the position for {0} to {1}..
        /// </summary>
        public static string ChannelsMoved {
            get {
                return ResourceManager.GetString("ChannelsMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not any matching overwrites to copy..
        /// </summary>
        public static string ChannelsNoCopyableOverwrite {
            get {
                return ResourceManager.GetString("ChannelsNoCopyableOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no overwrite for {0} on {1}..
        /// </summary>
        public static string ChannelsNoOverwrite {
            get {
                return ResourceManager.GetString("ChannelsNoOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed the topic for {0}..
        /// </summary>
        public static string ChannelsRemovedTopic {
            get {
                return ResourceManager.GetString("ChannelsRemovedTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Overwrites.
        /// </summary>
        public static string ChannelsTitleAllOverwrites {
            get {
                return ResourceManager.GetString("ChannelsTitleAllOverwrites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Overwrites.
        /// </summary>
        public static string ChannelsTitleAllOverwritesRoles {
            get {
                return ResourceManager.GetString("ChannelsTitleAllOverwritesRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Overwrites.
        /// </summary>
        public static string ChannelsTitleAllOverwritesUsers {
            get {
                return ResourceManager.GetString("ChannelsTitleAllOverwritesUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Channel Positions.
        /// </summary>
        public static string ChannelsTitleChannelPositions {
            get {
                return ResourceManager.GetString("ChannelsTitleChannelPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} On {1}.
        /// </summary>
        public static string ChannelsTitleSingleOverwrite {
            get {
                return ResourceManager.GetString("ChannelsTitleSingleOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added {0} as roles required to use {1}..
        /// </summary>
        public static string EmotesAddedRequiredRoles {
            get {
                return ResourceManager.GetString("EmotesAddedRequiredRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully enqueued creating the emote {0} at position {1}..
        /// </summary>
        public static string EmotesEnqueuedCreation {
            get {
                return ResourceManager.GetString("EmotesEnqueuedCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed {0} as roles required to use {1}..
        /// </summary>
        public static string EmotesRemovedRequiredRoles {
            get {
                return ResourceManager.GetString("EmotesRemovedRequiredRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Emotes.
        /// </summary>
        public static string EmotesTitleDisplay {
            get {
                return ResourceManager.GetString("EmotesTitleDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_Messages.
        /// </summary>
        public static string GetsFileMessages {
            get {
                return ResourceManager.GetString("GetsFileMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Joins.
        /// </summary>
        public static string GetsFileUserJoins {
            get {
                return ResourceManager.GetString("GetsFileUserJoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users_With_Reason.
        /// </summary>
        public static string GetsFileUsersWithReason {
            get {
                return ResourceManager.GetString("GetsFileUsersWithReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Info.
        /// </summary>
        public static string GetsFooterChannel {
            get {
                return ResourceManager.GetString("GetsFooterChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emote Info.
        /// </summary>
        public static string GetsFooterEmote {
            get {
                return ResourceManager.GetString("GetsFooterEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild Info.
        /// </summary>
        public static string GetsFooterGuild {
            get {
                return ResourceManager.GetString("GetsFooterGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild Users Info.
        /// </summary>
        public static string GetsFooterGuildUsers {
            get {
                return ResourceManager.GetString("GetsFooterGuildUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Info.
        /// </summary>
        public static string GetsFooterInvite {
            get {
                return ResourceManager.GetString("GetsFooterInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Info.
        /// </summary>
        public static string GetsFooterRole {
            get {
                return ResourceManager.GetString("GetsFooterRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shards Info.
        /// </summary>
        public static string GetsFooterShards {
            get {
                return ResourceManager.GetString("GetsFooterShards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Info.
        /// </summary>
        public static string GetsFooterUser {
            get {
                return ResourceManager.GetString("GetsFooterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhook Info.
        /// </summary>
        public static string GetsFooterWebhook {
            get {
                return ResourceManager.GetString("GetsFooterWebhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Owner: {1}.
        /// </summary>
        public static string GetsGuilds {
            get {
                return ResourceManager.GetString("GetsGuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (#{1}).
        /// </summary>
        public static string GetsJoinedAt {
            get {
                return ResourceManager.GetString("GetsJoinedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has the following permissions: {1}..
        /// </summary>
        public static string GetsShowEnumNames {
            get {
                return ResourceManager.GetString("GetsShowEnumNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string GetsTitleActivities {
            get {
                return ResourceManager.GetString("GetsTitleActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string GetsTitleActivity {
            get {
                return ResourceManager.GetString("GetsTitleActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afk Channel.
        /// </summary>
        public static string GetsTitleAfkChannel {
            get {
                return ResourceManager.GetString("GetsTitleAfkChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animated Emote Count.
        /// </summary>
        public static string GetsTitleAnimatedEmoteCount {
            get {
                return ResourceManager.GetString("GetsTitleAnimatedEmoteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Count.
        /// </summary>
        public static string GetsTitleBotCount {
            get {
                return ResourceManager.GetString("GetsTitleBotCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Channel Count.
        /// </summary>
        public static string GetsTitleCategoryChannelCount {
            get {
                return ResourceManager.GetString("GetsTitleCategoryChannelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string GetsTitleChannel {
            get {
                return ResourceManager.GetString("GetsTitleChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Count.
        /// </summary>
        public static string GetsTitleChannelCount {
            get {
                return ResourceManager.GetString("GetsTitleChannelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Info.
        /// </summary>
        public static string GetsTitleChannelInfo {
            get {
                return ResourceManager.GetString("GetsTitleChannelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Colons.
        /// </summary>
        public static string GetsTitleColons {
            get {
                return ResourceManager.GetString("GetsTitleColons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string GetsTitleColor {
            get {
                return ResourceManager.GetString("GetsTitleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string GetsTitleCreator {
            get {
                return ResourceManager.GetString("GetsTitleCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Self Deafened.
        /// </summary>
        public static string GetsTitleDeafen {
            get {
                return ResourceManager.GetString("GetsTitleDeafen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Channel.
        /// </summary>
        public static string GetsTitleDefaultChannel {
            get {
                return ResourceManager.GetString("GetsTitleDefaultChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed Channel.
        /// </summary>
        public static string GetsTitleEmbedChannel {
            get {
                return ResourceManager.GetString("GetsTitleEmbedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emote Count.
        /// </summary>
        public static string GetsTitleEmoteCount {
            get {
                return ResourceManager.GetString("GetsTitleEmoteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emote Info.
        /// </summary>
        public static string GetsTitleEmoteInfo {
            get {
                return ResourceManager.GetString("GetsTitleEmoteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum Names.
        /// </summary>
        public static string GetsTitleEnumNames {
            get {
                return ResourceManager.GetString("GetsTitleEnumNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild Features.
        /// </summary>
        public static string GetsTitleFeatures {
            get {
                return ResourceManager.GetString("GetsTitleFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guilds.
        /// </summary>
        public static string GetsTitleGuilds {
            get {
                return ResourceManager.GetString("GetsTitleGuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Hoisted.
        /// </summary>
        public static string GetsTitleHoisted {
            get {
                return ResourceManager.GetString("GetsTitleHoisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Ignored From Commands.
        /// </summary>
        public static string GetsTitleIgnoredCommands {
            get {
                return ResourceManager.GetString("GetsTitleIgnoredCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Ignored From Log.
        /// </summary>
        public static string GetsTitleIgnoredLog {
            get {
                return ResourceManager.GetString("GetsTitleIgnoredLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Image Log.
        /// </summary>
        public static string GetsTitleImageLog {
            get {
                return ResourceManager.GetString("GetsTitleImageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Image Only.
        /// </summary>
        public static string GetsTitleImageOnly {
            get {
                return ResourceManager.GetString("GetsTitleImageOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Voice Count.
        /// </summary>
        public static string GetsTitleInVoiceCount {
            get {
                return ResourceManager.GetString("GetsTitleInVoiceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined At.
        /// </summary>
        public static string GetsTitleJoined {
            get {
                return ResourceManager.GetString("GetsTitleJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Emote Count.
        /// </summary>
        public static string GetsTitleLocalEmoteCount {
            get {
                return ResourceManager.GetString("GetsTitleLocalEmoteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Managed.
        /// </summary>
        public static string GetsTitleManaged {
            get {
                return ResourceManager.GetString("GetsTitleManaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed Emote Count.
        /// </summary>
        public static string GetsTitleManagedEmoteCount {
            get {
                return ResourceManager.GetString("GetsTitleManagedEmoteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Mentionable.
        /// </summary>
        public static string GetsTitleMentionable {
            get {
                return ResourceManager.GetString("GetsTitleMentionable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Mod Log.
        /// </summary>
        public static string GetsTitleModLog {
            get {
                return ResourceManager.GetString("GetsTitleModLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Self Muted.
        /// </summary>
        public static string GetsTitleMute {
            get {
                return ResourceManager.GetString("GetsTitleMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string GetsTitleNickname {
            get {
                return ResourceManager.GetString("GetsTitleNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Nickname Count.
        /// </summary>
        public static string GetsTitleNicknameCount {
            get {
                return ResourceManager.GetString("GetsTitleNicknameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Notification Level.
        /// </summary>
        public static string GetsTitleNotifications {
            get {
                return ResourceManager.GetString("GetsTitleNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string GetsTitleOwner {
            get {
                return ResourceManager.GetString("GetsTitleOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string GetsTitlePermissions {
            get {
                return ResourceManager.GetString("GetsTitlePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string GetsTitlePosition {
            get {
                return ResourceManager.GetString("GetsTitlePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Count.
        /// </summary>
        public static string GetsTitleRoleCount {
            get {
                return ResourceManager.GetString("GetsTitleRoleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string GetsTitleRoles {
            get {
                return ResourceManager.GetString("GetsTitleRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Server Deafened.
        /// </summary>
        public static string GetsTitleServerDeafen {
            get {
                return ResourceManager.GetString("GetsTitleServerDeafen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Server Log.
        /// </summary>
        public static string GetsTitleServerLog {
            get {
                return ResourceManager.GetString("GetsTitleServerLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Server Muted.
        /// </summary>
        public static string GetsTitleServerMute {
            get {
                return ResourceManager.GetString("GetsTitleServerMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string GetsTitleStatus {
            get {
                return ResourceManager.GetString("GetsTitleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statuses.
        /// </summary>
        public static string GetsTitleStatuses {
            get {
                return ResourceManager.GetString("GetsTitleStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Channel.
        /// </summary>
        public static string GetsTitleSystemChannel {
            get {
                return ResourceManager.GetString("GetsTitleSystemChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Channel Count.
        /// </summary>
        public static string GetsTitleTextChannelCount {
            get {
                return ResourceManager.GetString("GetsTitleTextChannelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Channels.
        /// </summary>
        public static string GetsTitleTextChannels {
            get {
                return ResourceManager.GetString("GetsTitleTextChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Count.
        /// </summary>
        public static string GetsTitleUserCount {
            get {
                return ResourceManager.GetString("GetsTitleUserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string GetsTitleUsers {
            get {
                return ResourceManager.GetString("GetsTitleUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses.
        /// </summary>
        public static string GetsTitleUses {
            get {
                return ResourceManager.GetString("GetsTitleUses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Level.
        /// </summary>
        public static string GetsTitleVerification {
            get {
                return ResourceManager.GetString("GetsTitleVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Channel.
        /// </summary>
        public static string GetsTitleVoiceChannel {
            get {
                return ResourceManager.GetString("GetsTitleVoiceChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Channel Count.
        /// </summary>
        public static string GetsTitleVoiceChannelCount {
            get {
                return ResourceManager.GetString("GetsTitleVoiceChannelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Channels.
        /// </summary>
        public static string GetsTitleVoiceChannels {
            get {
                return ResourceManager.GetString("GetsTitleVoiceChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Info.
        /// </summary>
        public static string GetsTitleVoiceInfo {
            get {
                return ResourceManager.GetString("GetsTitleVoiceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Region.
        /// </summary>
        public static string GetsTitleVoiceRegion {
            get {
                return ResourceManager.GetString("GetsTitleVoiceRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhook Count.
        /// </summary>
        public static string GetsTitleWebhookCount {
            get {
                return ResourceManager.GetString("GetsTitleWebhookCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is #{1} to join the guild on {2}..
        /// </summary>
        public static string GetsUserJoinPosition {
            get {
                return ResourceManager.GetString("GetsUserJoinPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} joined on {1}.
        /// </summary>
        public static string GetsUserJoins {
            get {
                return ResourceManager.GetString("GetsUserJoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully enqueued modifying the splash image for this guild at position {0}..
        /// </summary>
        public static string GuildsEnqueuedSplash {
            get {
                return ResourceManager.GetString("GuildsEnqueuedSplash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully left {0}..
        /// </summary>
        public static string GuildsLeftGuild {
            get {
                return ResourceManager.GetString("GuildsLeftGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the AFK channel for this guild to {0}..
        /// </summary>
        public static string GuildsModifiedAfkChannel {
            get {
                return ResourceManager.GetString("GuildsModifiedAfkChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the AFK timeout for this guild to {0}..
        /// </summary>
        public static string GuildsModifiedAfkTime {
            get {
                return ResourceManager.GetString("GuildsModifiedAfkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the explicit content filter level for this guild to {0}..
        /// </summary>
        public static string GuildsModifiedContentFilter {
            get {
                return ResourceManager.GetString("GuildsModifiedContentFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the default message notification level for this guild to {0}..
        /// </summary>
        public static string GuildsModifiedMsgNotif {
            get {
                return ResourceManager.GetString("GuildsModifiedMsgNotif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the owner for this guild to {0}..
        /// </summary>
        public static string GuildsModifiedOwner {
            get {
                return ResourceManager.GetString("GuildsModifiedOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the voice region for this guild to {0} minutes..
        /// </summary>
        public static string GuildsModifiedRegion {
            get {
                return ResourceManager.GetString("GuildsModifiedRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the system channel for this guild to {0}..
        /// </summary>
        public static string GuildsModifiedSystemChannel {
            get {
                return ResourceManager.GetString("GuildsModifiedSystemChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the system channel boost messages to {0}..
        /// </summary>
        public static string GuildsModifiedSystemMessageBoost {
            get {
                return ResourceManager.GetString("GuildsModifiedSystemMessageBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the system channel welcome messages to {0}..
        /// </summary>
        public static string GuildsModifiedSystemMessageWelcome {
            get {
                return ResourceManager.GetString("GuildsModifiedSystemMessageWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the verification level for this guild to {0}..
        /// </summary>
        public static string GuildsModifiedVerif {
            get {
                return ResourceManager.GetString("GuildsModifiedVerif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed the splash image for this guild..
        /// </summary>
        public static string GuildsRemovedSplash {
            get {
                return ResourceManager.GetString("GuildsRemovedSplash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Ids.
        /// </summary>
        public static string GuildsTitleRegionIds {
            get {
                return ResourceManager.GetString("GuildsTitleRegionIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nothing.
        /// </summary>
        public static string GuildsVariableNothing {
            get {
                return ResourceManager.GetString("GuildsVariableNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted {0} matching invites..
        /// </summary>
        public static string InvitesDeletedMultipleInvites {
            get {
                return ResourceManager.GetString("InvitesDeletedMultipleInvites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find any invites matching the given conditions..
        /// </summary>
        public static string InvitesNoInviteMatches {
            get {
                return ResourceManager.GetString("InvitesNoInviteMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invites.
        /// </summary>
        public static string InvitesTitleDisplay {
            get {
                return ResourceManager.GetString("InvitesTitleDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank: {0} out of {1}
        ///Xp: {2}
        ///Level: {3}.
        /// </summary>
        public static string LevelsLevelDescription {
            get {
                return ResourceManager.GetString("LevelsLevelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xp Information.
        /// </summary>
        public static string LevelsLevelFooter {
            get {
                return ResourceManager.GetString("LevelsLevelFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Xp Information for {1}.
        /// </summary>
        public static string LevelsLevelTitle {
            get {
                return ResourceManager.GetString("LevelsLevelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has no {1} xp..
        /// </summary>
        public static string LevelsNoXp {
            get {
                return ResourceManager.GetString("LevelsNoXp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. {1}: [Xp: {2}, Level: {3}].
        /// </summary>
        public static string LevelsTopDescription {
            get {
                return ResourceManager.GetString("LevelsTopDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Ranks Information.
        /// </summary>
        public static string LevelsTopFooter {
            get {
                return ResourceManager.GetString("LevelsTopFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top {0} Ranks.
        /// </summary>
        public static string LevelsTopTitle {
            get {
                return ResourceManager.GetString("LevelsTopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to channel.
        /// </summary>
        public static string LevelsVariableChannel {
            get {
                return ResourceManager.GetString("LevelsVariableChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global.
        /// </summary>
        public static string LevelsVariableGlobal {
            get {
                return ResourceManager.GetString("LevelsVariableGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guild.
        /// </summary>
        public static string LevelsVariableGuild {
            get {
                return ResourceManager.GetString("LevelsVariableGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully bumped the listed invite..
        /// </summary>
        public static string ListedInviteBumped {
            get {
                return ResourceManager.GetString("ListedInviteBumped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created a listed invite from {0}..
        /// </summary>
        public static string ListedInviteCreated {
            get {
                return ResourceManager.GetString("ListedInviteCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted the listed invite..
        /// </summary>
        public static string ListedInviteDeleted {
            get {
                return ResourceManager.GetString("ListedInviteDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find an invite with the supplied options..
        /// </summary>
        public static string ListedInviteNoInviteMatch {
            get {
                return ResourceManager.GetString("ListedInviteNoInviteMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find a suitable invite; too many were found..
        /// </summary>
        public static string ListedInviteTooManyMatches {
            get {
                return ResourceManager.GetString("ListedInviteTooManyMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully set the log actions back to default..
        /// </summary>
        public static string LoggingDefaultLogActions {
            get {
                return ResourceManager.GetString("LoggingDefaultLogActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully {0} every log action..
        /// </summary>
        public static string LoggingModifiedAllLogActions {
            get {
                return ResourceManager.GetString("LoggingModifiedAllLogActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully {0} the following channels: {1}..
        /// </summary>
        public static string LoggingModifiedIgnoredLogChannels {
            get {
                return ResourceManager.GetString("LoggingModifiedIgnoredLogChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully {0} the following log actions: {1}..
        /// </summary>
        public static string LoggingModifiedLogActions {
            get {
                return ResourceManager.GetString("LoggingModifiedLogActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed the {0} log..
        /// </summary>
        public static string LoggingRemoved {
            get {
                return ResourceManager.GetString("LoggingRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully set {0} as the {1} log..
        /// </summary>
        public static string LoggingSetLog {
            get {
                return ResourceManager.GetString("LoggingSetLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already the current {1} log..
        /// </summary>
        public static string LogParameterPreconditionError {
            get {
                return ResourceManager.GetString("LogParameterPreconditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not the current {0} log..
        /// </summary>
        public static string LogParameterPreconditionSummary {
            get {
                return ResourceManager.GetString("LogParameterPreconditionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no {0} to remove..
        /// </summary>
        public static string LogPreconditionError {
            get {
                return ResourceManager.GetString("LogPreconditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} log must exist..
        /// </summary>
        public static string LogPreconditionSummary {
            get {
                return ResourceManager.GetString("LogPreconditionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} means required.
        ///{1} means optional.
        ///{2} means or..
        /// </summary>
        public static string MiscBasicSyntax {
            get {
                return ResourceManager.GetString("MiscBasicSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MiscFooterHelp {
            get {
                return ResourceManager.GetString("MiscFooterHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} for commands from a category.
        ///
        ///{1}.
        /// </summary>
        public static string MiscGeneralCommandInfo {
            get {
                return ResourceManager.GetString("MiscGeneralCommandInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} for a list of commands.
        ///Type {1} for help with a command..
        /// </summary>
        public static string MiscGeneralHelp {
            get {
                return ResourceManager.GetString("MiscGeneralHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid help entry command number for {1}..
        /// </summary>
        public static string MiscInvalidHelpEntryNumber {
            get {
                return ResourceManager.GetString("MiscInvalidHelpEntryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GitHub Repository]({0})
        ///[Discord Server]({1}).
        /// </summary>
        public static string MiscLinks {
            get {
                return ResourceManager.GetString("MiscLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `User` means `@User|&quot;Username#Discriminator&quot;`
        ///`Role` means `@Role|&quot;Role name&quot;`
        ///`Channel` means `#Channel|&quot;Channel name&quot;`.
        /// </summary>
        public static string MiscMentionSyntax {
            get {
                return ResourceManager.GetString("MiscMentionSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added a reminder which will trigger in {0}..
        /// </summary>
        public static string MiscRemind {
            get {
                return ResourceManager.GetString("MiscRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Able To Be Toggled.
        /// </summary>
        public static string MiscTitleAbleToBeToggled {
            get {
                return ResourceManager.GetString("MiscTitleAbleToBeToggled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases.
        /// </summary>
        public static string MiscTitleAliases {
            get {
                return ResourceManager.GetString("MiscTitleAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Commands.
        /// </summary>
        public static string MiscTitleAllCommands {
            get {
                return ResourceManager.GetString("MiscTitleAllCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Permissions.
        /// </summary>
        public static string MiscTitleBasePermissions {
            get {
                return ResourceManager.GetString("MiscTitleBasePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Syntax.
        /// </summary>
        public static string MiscTitleBasicSyntax {
            get {
                return ResourceManager.GetString("MiscTitleBasicSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string MiscTitleCategories {
            get {
                return ResourceManager.GetString("MiscTitleCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands In {0}.
        /// </summary>
        public static string MiscTitleCategoryCommands {
            get {
                return ResourceManager.GetString("MiscTitleCategoryCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string MiscTitleCommands {
            get {
                return ResourceManager.GetString("MiscTitleCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Enabled.
        /// </summary>
        public static string MiscTitleCurrentlyEnabled {
            get {
                return ResourceManager.GetString("MiscTitleCurrentlyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string MiscTitleDescription {
            get {
                return ResourceManager.GetString("MiscTitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled By Default.
        /// </summary>
        public static string MiscTitleEnabledByDefault {
            get {
                return ResourceManager.GetString("MiscTitleEnabledByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Help.
        /// </summary>
        public static string MiscTitleGeneralHelp {
            get {
                return ResourceManager.GetString("MiscTitleGeneralHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string MiscTitleLinks {
            get {
                return ResourceManager.GetString("MiscTitleLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mention Syntax.
        /// </summary>
        public static string MiscTitleMentionSyntax {
            get {
                return ResourceManager.GetString("MiscTitleMentionSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named Arguments.
        /// </summary>
        public static string MiscTitleNamedArguments {
            get {
                return ResourceManager.GetString("MiscTitleNamedArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submodules.
        /// </summary>
        public static string MiscTitleSubmodules {
            get {
                return ResourceManager.GetString("MiscTitleSubmodules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the nickname for {0} to {1}..
        /// </summary>
        public static string NicknamesModifiedNickname {
            get {
                return ResourceManager.GetString("NicknamesModifiedNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed the nickname for {0}..
        /// </summary>
        public static string NicknamesRemovedNickname {
            get {
                return ResourceManager.GetString("NicknamesRemovedNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully set {0} back to default..
        /// </summary>
        public static string NotificationDefault {
            get {
                return ResourceManager.GetString("NotificationDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully disabled {0}..
        /// </summary>
        public static string NotificationDisabled {
            get {
                return ResourceManager.GetString("NotificationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the channel for {0} to {1}..
        /// </summary>
        public static string NotificationModifedChannel {
            get {
                return ResourceManager.GetString("NotificationModifedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the content for {0} to {1}..
        /// </summary>
        public static string NotificationModifiedContent {
            get {
                return ResourceManager.GetString("NotificationModifiedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the embed for {0} to.
        /// </summary>
        public static string NotificationModifiedEmbed {
            get {
                return ResourceManager.GetString("NotificationModifiedEmbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send the {0} notification because it has no channel..
        /// </summary>
        public static string NotificationSendNoChannel {
            get {
                return ResourceManager.GetString("NotificationSendNoChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send the {0} notification because it does not exist..
        /// </summary>
        public static string NotificationSendNull {
            get {
                return ResourceManager.GetString("NotificationSendNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully gave {0} the persistent role {1}..
        /// </summary>
        public static string PersistentRolesGave {
            get {
                return ResourceManager.GetString("PersistentRolesGave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed the persistent role {0} from {1}..
        /// </summary>
        public static string PersistentRolesRemoved {
            get {
                return ResourceManager.GetString("PersistentRolesRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added the quote {0}..
        /// </summary>
        public static string QuotesAddedQuote {
            get {
                return ResourceManager.GetString("QuotesAddedQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quote {0} has no description..
        /// </summary>
        public static string QuotesNoDescription {
            get {
                return ResourceManager.GetString("QuotesNoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed the quote {0}..
        /// </summary>
        public static string QuotesRemovedQuote {
            get {
                return ResourceManager.GetString("QuotesRemovedQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created a reminder for {0} minutes..
        /// </summary>
        public static string RemindersAddedRemind {
            get {
                return ResourceManager.GetString("RemindersAddedRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the position for {0} to {1}..
        /// </summary>
        public static string RoleMoved {
            get {
                return ResourceManager.GetString("RoleMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully cleared as many permissions as allowed from {0}..
        /// </summary>
        public static string RolesClearedPermissions {
            get {
                return ResourceManager.GetString("RolesClearedPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully copied {0} from {1} to {2}..
        /// </summary>
        public static string RolesCopiedPermissions {
            get {
                return ResourceManager.GetString("RolesCopiedPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully gave {0} to {1}..
        /// </summary>
        public static string RolesGave {
            get {
                return ResourceManager.GetString("RolesGave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the color for {0} to #{1}..
        /// </summary>
        public static string RolesModifiedColor {
            get {
                return ResourceManager.GetString("RolesModifiedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the hosted status for {0} to {1}..
        /// </summary>
        public static string RolesModifiedHoistedStatus {
            get {
                return ResourceManager.GetString("RolesModifiedHoistedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the mentionable status for {0} to {1}..
        /// </summary>
        public static string RolesModifiedMentionability {
            get {
                return ResourceManager.GetString("RolesModifiedMentionability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully allowed {0} for {1}..
        /// </summary>
        public static string RolesModifiedPermissionsAllow {
            get {
                return ResourceManager.GetString("RolesModifiedPermissionsAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully denied {0} for {1}..
        /// </summary>
        public static string RolesModifiedPermissionsDeny {
            get {
                return ResourceManager.GetString("RolesModifiedPermissionsDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RolesTitleDisplay {
            get {
                return ResourceManager.GetString("RolesTitleDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions For {0}.
        /// </summary>
        public static string RolesTitleDisplayPermissions {
            get {
                return ResourceManager.GetString("RolesTitleDisplayPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully took {0} from {1}..
        /// </summary>
        public static string RolesTook {
            get {
                return ResourceManager.GetString("RolesTook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added a rule to the category {0}..
        /// </summary>
        public static string RulesAddedRule {
            get {
                return ResourceManager.GetString("RulesAddedRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created the rule category {0}..
        /// </summary>
        public static string RulesCreatedCategory {
            get {
                return ResourceManager.GetString("RulesCreatedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted the rule category {0}..
        /// </summary>
        public static string RulesDeletedCategory {
            get {
                return ResourceManager.GetString("RulesDeletedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid position to insert a rule at..
        /// </summary>
        public static string RulesInvalidRuleInsert {
            get {
                return ResourceManager.GetString("RulesInvalidRuleInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid position to remove a rule at..
        /// </summary>
        public static string RulesInvalidRuleRemove {
            get {
                return ResourceManager.GetString("RulesInvalidRuleRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully changed the value of the category {0} to {1}..
        /// </summary>
        public static string RulesModifiedCategoryValue {
            get {
                return ResourceManager.GetString("RulesModifiedCategoryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully changed the value of the rule {0} to {1}..
        /// </summary>
        public static string RulesModifiedRuleValue {
            get {
                return ResourceManager.GetString("RulesModifiedRuleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed a rule at #{0} in the category {1}..
        /// </summary>
        public static string RulesRemovedRule {
            get {
                return ResourceManager.GetString("RulesRemovedRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied rule already exists..
        /// </summary>
        public static string RulesRuleAlreadyExists {
            get {
                return ResourceManager.GetString("RulesRuleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully swapped the rule categories #{0} ({1} rules) and #{2} ({3} rules)..
        /// </summary>
        public static string RulesSwappedRuleCategories {
            get {
                return ResourceManager.GetString("RulesSwappedRuleCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully swapped the rules #{0} and #{1] in the category {2}..
        /// </summary>
        public static string RulesSwappedRules {
            get {
                return ResourceManager.GetString("RulesSwappedRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added {0}..
        /// </summary>
        public static string SelfRolesAdded {
            get {
                return ResourceManager.GetString("SelfRolesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added {0} and removed all conflicting self roles..
        /// </summary>
        public static string SelfRolesAddedAndRemovedOthers {
            get {
                return ResourceManager.GetString("SelfRolesAddedAndRemovedOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added {0} self roles to group {1}..
        /// </summary>
        public static string SelfRolesAddedToGroup {
            get {
                return ResourceManager.GetString("SelfRolesAddedToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully cleared {0} self roles from group {1}..
        /// </summary>
        public static string SelfRolesClearedGroup {
            get {
                return ResourceManager.GetString("SelfRolesClearedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed {0}..
        /// </summary>
        public static string SelfRolesRemoved {
            get {
                return ResourceManager.GetString("SelfRolesRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed {0} self roles..
        /// </summary>
        public static string SelfRolesRemovedFromGroup {
            get {
                return ResourceManager.GetString("SelfRolesRemovedFromGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Assignable Roles.
        /// </summary>
        public static string SelfRolesTitleDisplay {
            get {
                return ResourceManager.GetString("SelfRolesTitleDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully cleared the command overrides for {0}..
        /// </summary>
        public static string SettingsClearedCommands {
            get {
                return ResourceManager.GetString("SettingsClearedCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully disabled and set the priority to {0} for {1}..
        /// </summary>
        public static string SettingsDisabledCommands {
            get {
                return ResourceManager.GetString("SettingsDisabledCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully enabled and set the priority to {0} for {1}..
        /// </summary>
        public static string SettingsEnabledCommands {
            get {
                return ResourceManager.GetString("SettingsEnabledCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created {0}..
        /// </summary>
        public static string SnowflakesCreated {
            get {
                return ResourceManager.GetString("SnowflakesCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted {0}..
        /// </summary>
        public static string SnowflakesDeleted {
            get {
                return ResourceManager.GetString("SnowflakesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully queued changing the icon for {0} at position {1}..
        /// </summary>
        public static string SnowflakesEnqueuedIcon {
            get {
                return ResourceManager.GetString("SnowflakesEnqueuedIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the name of {0} to {1}..
        /// </summary>
        public static string SnowflakesModifiedName {
            get {
                return ResourceManager.GetString("SnowflakesModifiedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed the icon for {0}..
        /// </summary>
        public static string SnowflakesRemovedIcon {
            get {
                return ResourceManager.GetString("SnowflakesRemovedIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully soft deleted {0}..
        /// </summary>
        public static string SnowflakesSoftDeleted {
            get {
                return ResourceManager.GetString("SnowflakesSoftDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} prevention is already disabled..
        /// </summary>
        public static string SpamPreventionAlreadyDisabled {
            get {
                return ResourceManager.GetString("SpamPreventionAlreadyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} prevention is already enabled..
        /// </summary>
        public static string SpamPreventionAlreadyEnabled {
            get {
                return ResourceManager.GetString("SpamPreventionAlreadyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created {0} {1} prevention..
        /// </summary>
        public static string SpamPreventionCreated {
            get {
                return ResourceManager.GetString("SpamPreventionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully disabled the {0} {1} prevention..
        /// </summary>
        public static string SpamPreventionDisabled {
            get {
                return ResourceManager.GetString("SpamPreventionDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully enabled the {0} {1} prevention..
        /// </summary>
        public static string SpamPreventionEnabled {
            get {
                return ResourceManager.GetString("SpamPreventionEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find a {0} {1} prevention..
        /// </summary>
        public static string SpamPreventionNotFound {
            get {
                return ResourceManager.GetString("SpamPreventionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully {0} {1}..
        /// </summary>
        public static string UsersActionDone {
            get {
                return ResourceManager.GetString("UsersActionDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already in {1}..
        /// </summary>
        public static string UsersAlreadyInChannel {
            get {
                return ResourceManager.GetString("UsersAlreadyInChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot give the same role being gathered..
        /// </summary>
        public static string UsersCannotGiveRoleBeingGathered {
            get {
                return ResourceManager.GetString("UsersCannotGiveRoleBeingGathered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted {0} message(s) on {1} from {2}..
        /// </summary>
        public static string UsersDeletedMessages {
            get {
                return ResourceManager.GetString("UsersDeletedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted {0} message(s) on {1}..
        /// </summary>
        public static string UsersDeletedMessagesNoTarget {
            get {
                return ResourceManager.GetString("UsersDeletedMessagesNoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a Discord user..
        /// </summary>
        public static string UsersDoesNotExist {
            get {
                return ResourceManager.GetString("UsersDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would have pruned {0} guild members with a prune period of {1} days..
        /// </summary>
        public static string UsersFakePrune {
            get {
                return ResourceManager.GetString("UsersFakePrune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the voice channel for {0} to {1}..
        /// </summary>
        public static string UsersMoved {
            get {
                return ResourceManager.GetString("UsersMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to bulk modify {0} users. ETA on completion: {1} seconds..
        /// </summary>
        public static string UsersMultiUserActionProgress {
            get {
                return ResourceManager.GetString("UsersMultiUserActionProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully bulk modified {0} users..
        /// </summary>
        public static string UsersMultiUserActionSuccess {
            get {
                return ResourceManager.GetString("UsersMultiUserActionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ban reason listed..
        /// </summary>
        public static string UsersNoBanReason {
            get {
                return ResourceManager.GetString("UsersNoBanReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully pruned {0} guild members with a prune period of {1} days..
        /// </summary>
        public static string UsersRealPrune {
            get {
                return ResourceManager.GetString("UsersRealPrune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban Reason For {0}.
        /// </summary>
        public static string UsersTitleBanReason {
            get {
                return ResourceManager.GetString("UsersTitleBanReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bans.
        /// </summary>
        public static string UsersTitleBans {
            get {
                return ResourceManager.GetString("UsersTitleBans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They will be {0} in {1}..
        /// </summary>
        public static string UsersUnpunishedTime {
            get {
                return ResourceManager.GetString("UsersUnpunishedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added.
        /// </summary>
        public static string VariableAdded {
            get {
                return ResourceManager.GetString("VariableAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string VariableAll {
            get {
                return ResourceManager.GetString("VariableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  + .
        /// </summary>
        public static string VariableAnd {
            get {
                return ResourceManager.GetString("VariableAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to banned.
        /// </summary>
        public static string VariableBanned {
            get {
                return ResourceManager.GetString("VariableBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Category].
        /// </summary>
        public static string VariableCategoryParameter {
            get {
                return ResourceManager.GetString("VariableCategoryParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deafened.
        /// </summary>
        public static string VariableDeafened {
            get {
                return ResourceManager.GetString("VariableDeafened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled.
        /// </summary>
        public static string VariableDisabled {
            get {
                return ResourceManager.GetString("VariableDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enabled.
        /// </summary>
        public static string VariableEnabled {
            get {
                return ResourceManager.GetString("VariableEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ignored.
        /// </summary>
        public static string VariableIgnored {
            get {
                return ResourceManager.GetString("VariableIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        public static string VariableImageLog {
            get {
                return ResourceManager.GetString("VariableImageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid user.
        /// </summary>
        public static string VariableInvalidUser {
            get {
                return ResourceManager.GetString("VariableInvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kicked.
        /// </summary>
        public static string VariableKicked {
            get {
                return ResourceManager.GetString("VariableKicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mod.
        /// </summary>
        public static string VariableModLog {
            get {
                return ResourceManager.GetString("VariableModLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to muted.
        /// </summary>
        public static string VariableMuted {
            get {
                return ResourceManager.GetString("VariableMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string VariableName {
            get {
                return ResourceManager.GetString("VariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None..
        /// </summary>
        public static string VariableNone {
            get {
                return ResourceManager.GetString("VariableNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string VariableNotApplicable {
            get {
                return ResourceManager.GetString("VariableNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string VariableNothing {
            get {
                return ResourceManager.GetString("VariableNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string VariableOptionalLeft {
            get {
                return ResourceManager.GetString("VariableOptionalLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string VariableOptionalRight {
            get {
                return ResourceManager.GetString("VariableOptionalRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  | .
        /// </summary>
        public static string VariableOr {
            get {
                return ResourceManager.GetString("VariableOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotes.
        /// </summary>
        public static string VariableQuotes {
            get {
                return ResourceManager.GetString("VariableQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raid.
        /// </summary>
        public static string VariableRaid {
            get {
                return ResourceManager.GetString("VariableRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regex.
        /// </summary>
        public static string VariableRegex {
            get {
                return ResourceManager.GetString("VariableRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removed.
        /// </summary>
        public static string VariableRemoved {
            get {
                return ResourceManager.GetString("VariableRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [.
        /// </summary>
        public static string VariableRequiredLeft {
            get {
                return ResourceManager.GetString("VariableRequiredLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ].
        /// </summary>
        public static string VariableRequiredRight {
            get {
                return ResourceManager.GetString("VariableRequiredRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server.
        /// </summary>
        public static string VariableServerLog {
            get {
                return ResourceManager.GetString("VariableServerLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to soft banned.
        /// </summary>
        public static string VariableSoftBanned {
            get {
                return ResourceManager.GetString("VariableSoftBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spam.
        /// </summary>
        public static string VariableSpam {
            get {
                return ResourceManager.GetString("VariableSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.
        /// </summary>
        public static string VariableString {
            get {
                return ResourceManager.GetString("VariableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unbanned.
        /// </summary>
        public static string VariableUnbanned {
            get {
                return ResourceManager.GetString("VariableUnbanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undeafened.
        /// </summary>
        public static string VariableUndeafened {
            get {
                return ResourceManager.GetString("VariableUndeafened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unignored.
        /// </summary>
        public static string VariableUnignored {
            get {
                return ResourceManager.GetString("VariableUnignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unmuted.
        /// </summary>
        public static string VariableUnmuted {
            get {
                return ResourceManager.GetString("VariableUnmuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unvoice-muted.
        /// </summary>
        public static string VariableUnvoiceMuted {
            get {
                return ResourceManager.GetString("VariableUnvoiceMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to voice-muted.
        /// </summary>
        public static string VariableVoiceMuted {
            get {
                return ResourceManager.GetString("VariableVoiceMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified the channel for {0} to {1}..
        /// </summary>
        public static string WebhooksModifiedChannel {
            get {
                return ResourceManager.GetString("WebhooksModifiedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhooks On {0}.
        /// </summary>
        public static string WebhooksTitleDisplayWebhooks {
            get {
                return ResourceManager.GetString("WebhooksTitleDisplayWebhooks", resourceCulture);
            }
        }
    }
}
