//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advobot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Summaries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Summaries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advobot.Resources.Summaries", typeof(Summaries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives or takes a role depending on if the user already has it. Removes all other roles in the same group unless the group is 0..
        /// </summary>
        public static string AssignSelfRole {
            get {
                return ResourceManager.GetString("AssignSelfRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bans the user from the guild..
        /// </summary>
        public static string Ban {
            get {
                return ResourceManager.GetString("Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bumps the invite on the guild..
        /// </summary>
        public static string Bump {
            get {
                return ResourceManager.GetString("Bump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears the permission overwrites from a channel..
        /// </summary>
        public static string ClearChannelPerms {
            get {
                return ResourceManager.GetString("ClearChannelPerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes all permissions from a role..
        /// </summary>
        public static string ClearRolePerms {
            get {
                return ResourceManager.GetString("ClearRolePerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the names and categories of commands..
        /// </summary>
        public static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies the permissions overwrites from one channel to another..
        /// </summary>
        public static string CopyChannelPerms {
            get {
                return ResourceManager.GetString("CopyChannelPerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies the permissions from one role to another..
        /// </summary>
        public static string CopyRolePerms {
            get {
                return ResourceManager.GetString("CopyRolePerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a channel..
        /// </summary>
        public static string CreateChannel {
            get {
                return ResourceManager.GetString("CreateChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates an emote..
        /// </summary>
        public static string CreateEmote {
            get {
                return ResourceManager.GetString("CreateEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a guild with the bot as owner..
        /// </summary>
        public static string CreateGuild {
            get {
                return ResourceManager.GetString("CreateGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates an invite..
        /// </summary>
        public static string CreateInvite {
            get {
                return ResourceManager.GetString("CreateInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a role..
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a voice channel and a role which restricts access to that voice channel..
        /// </summary>
        public static string CreateRoleRestrictedChannel {
            get {
                return ResourceManager.GetString("CreateRoleRestrictedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a webhook for the guild..
        /// </summary>
        public static string CreateWebhook {
            get {
                return ResourceManager.GetString("CreateWebhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text channel to create a webhook on..
        /// </summary>
        public static string CreateWebhookChannel {
            get {
                return ResourceManager.GetString("CreateWebhookChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name to give the webhook..
        /// </summary>
        public static string CreateWebhookName {
            get {
                return ResourceManager.GetString("CreateWebhookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents a user from hearing in voice chat..
        /// </summary>
        public static string Deafen {
            get {
                return ResourceManager.GetString("Deafen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes a channel..
        /// </summary>
        public static string DeleteChannel {
            get {
                return ResourceManager.GetString("DeleteChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes an emote..
        /// </summary>
        public static string DeleteEmote {
            get {
                return ResourceManager.GetString("DeleteEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the bot is the current owner of the guild, this command will delete the guild..
        /// </summary>
        public static string DeleteGuild {
            get {
                return ResourceManager.GetString("DeleteGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes an invite..
        /// </summary>
        public static string DeleteInvite {
            get {
                return ResourceManager.GetString("DeleteInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes multiple invites matching specified criteria..
        /// </summary>
        public static string DeleteMultipleInvites {
            get {
                return ResourceManager.GetString("DeleteMultipleInvites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes a role..
        /// </summary>
        public static string DeleteRole {
            get {
                return ResourceManager.GetString("DeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes a webhook from the guild..
        /// </summary>
        public static string DeleteWebhook {
            get {
                return ResourceManager.GetString("DeleteWebhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The webhook to delete..
        /// </summary>
        public static string DeleteWebhookWebhook {
            get {
                return ResourceManager.GetString("DeleteWebhookWebhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns the bot off..
        /// </summary>
        public static string DisconnectBot {
            get {
                return ResourceManager.GetString("DisconnectBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays all of the banned phrases in this guild..
        /// </summary>
        public static string DisplayBannedPhrases {
            get {
                return ResourceManager.GetString("DisplayBannedPhrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the permission overwrites on a channel..
        /// </summary>
        public static string DisplayChannelPerms {
            get {
                return ResourceManager.GetString("DisplayChannelPerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the positions of each channel..
        /// </summary>
        public static string DisplayChannelPosition {
            get {
                return ResourceManager.GetString("DisplayChannelPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays all the bans on the guild..
        /// </summary>
        public static string DisplayCurrentBanList {
            get {
                return ResourceManager.GetString("DisplayCurrentBanList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays all the emotes matching a specified criteria..
        /// </summary>
        public static string DisplayEmotes {
            get {
                return ResourceManager.GetString("DisplayEmotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays all the invites..
        /// </summary>
        public static string DisplayInvites {
            get {
                return ResourceManager.GetString("DisplayInvites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the persistent roles which exist in this guild..
        /// </summary>
        public static string DisplayPersistentRoles {
            get {
                return ResourceManager.GetString("DisplayPersistentRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the permissions .
        /// </summary>
        public static string DisplayRolePerms {
            get {
                return ResourceManager.GetString("DisplayRolePerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the positions of each role..
        /// </summary>
        public static string DisplayRolePositions {
            get {
                return ResourceManager.GetString("DisplayRolePositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the groups and roles which can be self assigned..
        /// </summary>
        public static string DisplaySelfRoles {
            get {
                return ResourceManager.GetString("DisplaySelfRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists all the webhooks on the guild or the specified channel..
        /// </summary>
        public static string DisplayWebhooks {
            get {
                return ResourceManager.GetString("DisplayWebhooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel to get webhooks from..
        /// </summary>
        public static string DisplayWebhooksChannel {
            get {
                return ResourceManager.GetString("DisplayWebhooksChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does an action on many users at once..
        /// </summary>
        public static string ForAllWithRole {
            get {
                return ResourceManager.GetString("ForAllWithRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays information about the specified character..
        /// </summary>
        public static string GachaCharacter {
            get {
                return ResourceManager.GetString("GachaCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gifts a character to a different user..
        /// </summary>
        public static string GachaGive {
            get {
                return ResourceManager.GetString("GachaGive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the characters you have claimed.
        /// </summary>
        public static string GachaHarem {
            get {
                return ResourceManager.GetString("GachaHarem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolls a random character that you can claim..
        /// </summary>
        public static string GachaRoll {
            get {
                return ResourceManager.GetString("GachaRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays information about the specified source..
        /// </summary>
        public static string GachaSource {
            get {
                return ResourceManager.GetString("GachaSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade characters with a different user..
        /// </summary>
        public static string GachaTrade {
            get {
                return ResourceManager.GetString("GachaTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A channel on the guild which you can see..
        /// </summary>
        public static string GenericChannelArgument {
            get {
                return ResourceManager.GetString("GenericChannelArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets an invite meeting the given criteria..
        /// </summary>
        public static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists the given reason for a user being banned..
        /// </summary>
        public static string GetBanReason {
            get {
                return ResourceManager.GetString("GetBanReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays all the value of an enum..
        /// </summary>
        public static string GetEnumNames {
            get {
                return ResourceManager.GetString("GetEnumNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the guilds the bot is in..
        /// </summary>
        public static string GetGuilds {
            get {
                return ResourceManager.GetString("GetGuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows information about specified things..
        /// </summary>
        public static string GetInfo {
            get {
                return ResourceManager.GetString("GetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the count of each item being logged..
        /// </summary>
        public static string GetLogCounters {
            get {
                return ResourceManager.GetString("GetLogCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads the past specified amount of messages..
        /// </summary>
        public static string GetMessages {
            get {
                return ResourceManager.GetString("GetMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays all the permissions that come from a specified value..
        /// </summary>
        public static string GetPermNamesFromValue {
            get {
                return ResourceManager.GetString("GetPermNamesFromValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the url for a user&apos;s avatar..
        /// </summary>
        public static string GetUserAvatar {
            get {
                return ResourceManager.GetString("GetUserAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the user which joined the guild at a specified position..
        /// </summary>
        public static string GetUserJoinedAt {
            get {
                return ResourceManager.GetString("GetUserJoinedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the users in the guild and the order they have joined..
        /// </summary>
        public static string GetUserJoinList {
            get {
                return ResourceManager.GetString("GetUserJoinList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds users matching some criteria..
        /// </summary>
        public static string GetUsersWithReason {
            get {
                return ResourceManager.GetString("GetUsersWithReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives roles to a user..
        /// </summary>
        public static string GiveRole {
            get {
                return ResourceManager.GetString("GiveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays information about commands..
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints out help information for a specific command in a specified module..
        /// </summary>
        public static string HelpCommandHelp {
            get {
                return ResourceManager.GetString("HelpCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints out general help information for the bot..
        /// </summary>
        public static string HelpGeneralHelp {
            get {
                return ResourceManager.GetString("HelpGeneralHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints out help information for a module..
        /// </summary>
        public static string HelpModuleHelp {
            get {
                return ResourceManager.GetString("HelpModuleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a command. This does not need to be exact; commands with similar names will be found..
        /// </summary>
        public static string HelpVariableCommand {
            get {
                return ResourceManager.GetString("HelpVariableCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of a command overload..
        /// </summary>
        public static string HelpVariableCommandPosition {
            get {
                return ResourceManager.GetString("HelpVariableCommandPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a command. This does need to be the exact name of a command and in quotes..
        /// </summary>
        public static string HelpVariableExactCommand {
            get {
                return ResourceManager.GetString("HelpVariableExactCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed a user from the guild..
        /// </summary>
        public static string Kick {
            get {
                return ResourceManager.GetString("Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes the bot leave the guild. Settings will be preserved..
        /// </summary>
        public static string LeaveGuild {
            get {
                return ResourceManager.GetString("LeaveGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the level of yourself or a different user..
        /// </summary>
        public static string LevelsShow {
            get {
                return ResourceManager.GetString("LevelsShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the highest leveled people in the server..
        /// </summary>
        public static string LevelsTop {
            get {
                return ResourceManager.GetString("LevelsTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays an embed with user supplied everything except fields..
        /// </summary>
        public static string MakeAnEmbed {
            get {
                return ResourceManager.GetString("MakeAnEmbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages the bot owner..
        /// </summary>
        public static string MessageBotOwner {
            get {
                return ResourceManager.GetString("MessageBotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentions an unmentionable role with a message..
        /// </summary>
        public static string MessageRole {
            get {
                return ResourceManager.GetString("MessageRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds or removes a guild from the public guild list..
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server log will send messages when these events happen..
        /// </summary>
        public static string ModifyActions {
            get {
                return ResourceManager.GetString("ModifyActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds or removes banned names..
        /// </summary>
        public static string ModifyBannedNames {
            get {
                return ResourceManager.GetString("ModifyBannedNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds or removes banned regex..
        /// </summary>
        public static string ModifyBannedRegex {
            get {
                return ResourceManager.GetString("ModifyBannedRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds or removes banned strings..
        /// </summary>
        public static string ModifyBannedStrings {
            get {
                return ResourceManager.GetString("ModifyBannedStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the bot&apos;s icon..
        /// </summary>
        public static string ModifyBotIcon {
            get {
                return ResourceManager.GetString("ModifyBotIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the bot&apos;s name..
        /// </summary>
        public static string ModifyBotName {
            get {
                return ResourceManager.GetString("ModifyBotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the bit rate on a voice channel..
        /// </summary>
        public static string ModifyChannelBitRate {
            get {
                return ResourceManager.GetString("ModifyChannelBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the amount of people who can be in a voice channel..
        /// </summary>
        public static string ModifyChannelLimit {
            get {
                return ResourceManager.GetString("ModifyChannelLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies a channel&apos;s name..
        /// </summary>
        public static string ModifyChannelName {
            get {
                return ResourceManager.GetString("ModifyChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles the nsfw option on a channel..
        /// </summary>
        public static string ModifyChannelNsfw {
            get {
                return ResourceManager.GetString("ModifyChannelNsfw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the permission overwrites on a channel..
        /// </summary>
        public static string ModifyChannelPerms {
            get {
                return ResourceManager.GetString("ModifyChannelPerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the position of a channel..
        /// </summary>
        public static string ModifyChannelPosition {
            get {
                return ResourceManager.GetString("ModifyChannelPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies a channel&apos;s topic..
        /// </summary>
        public static string ModifyChannelTopic {
            get {
                return ResourceManager.GetString("ModifyChannelTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns commands on and off..
        /// </summary>
        public static string ModifyCommands {
            get {
                return ResourceManager.GetString("ModifyCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears the command overrides on the specified entity..
        /// </summary>
        public static string ModifyCommandsClear {
            get {
                return ResourceManager.GetString("ModifyCommandsClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates or modifies a command override to a &apos;disallowed&apos; state with the supplied priority on the specified entity. A higher priority is used first..
        /// </summary>
        public static string ModifyCommandsDisable {
            get {
                return ResourceManager.GetString("ModifyCommandsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates or modifies a command override to an &apos;allowed&apos; state with the supplied priority on the specified entity. A higher priority is used first..
        /// </summary>
        public static string ModifyCommandsEnable {
            get {
                return ResourceManager.GetString("ModifyCommandsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies an emote name..
        /// </summary>
        public static string ModifyEmoteName {
            get {
                return ResourceManager.GetString("ModifyEmoteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the roles required to use an emote. Discord clients will need to be restarted before you can use the emote again..
        /// </summary>
        public static string ModifyEmoteRoles {
            get {
                return ResourceManager.GetString("ModifyEmoteRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies a message sent when a user leaves the server..
        /// </summary>
        public static string ModifyGoodbyeMessage {
            get {
                return ResourceManager.GetString("ModifyGoodbyeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies which channel is the afk channel..
        /// </summary>
        public static string ModifyGuildAfkChannel {
            get {
                return ResourceManager.GetString("ModifyGuildAfkChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies how long it takes to get moved to the afk channel..
        /// </summary>
        public static string ModifyGuildAfkTimer {
            get {
                return ResourceManager.GetString("ModifyGuildAfkTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified the guild&apos;s explicit content filter level..
        /// </summary>
        public static string ModifyGuildExplicitContentFilter {
            get {
                return ResourceManager.GetString("ModifyGuildExplicitContentFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the guild&apos;s icon..
        /// </summary>
        public static string ModifyGuildIcon {
            get {
                return ResourceManager.GetString("ModifyGuildIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the guild&apos;s default message notification setting..
        /// </summary>
        public static string ModifyGuildMsgNotif {
            get {
                return ResourceManager.GetString("ModifyGuildMsgNotif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the guild&apos;s name..
        /// </summary>
        public static string ModifyGuildName {
            get {
                return ResourceManager.GetString("ModifyGuildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the guild&apos;s region..
        /// </summary>
        public static string ModifyGuildRegion {
            get {
                return ResourceManager.GetString("ModifyGuildRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the guild&apos;s splash..
        /// </summary>
        public static string ModifyGuildSplash {
            get {
                return ResourceManager.GetString("ModifyGuildSplash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies which channel is the system channel..
        /// </summary>
        public static string ModifyGuildSystemChannel {
            get {
                return ResourceManager.GetString("ModifyGuildSystemChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the guild&apos;s verification level..
        /// </summary>
        public static string ModifyGuildVerif {
            get {
                return ResourceManager.GetString("ModifyGuildVerif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignores all logging info that would have been gotten from a channel..
        /// </summary>
        public static string ModifyIgnoredChannels {
            get {
                return ResourceManager.GetString("ModifyIgnoredChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bot will ignore commands said on these channels. If a command is input then the bot will instead ignore only that command on the given channel..
        /// </summary>
        public static string ModifyIgnoredCommandChannels {
            get {
                return ResourceManager.GetString("ModifyIgnoredCommandChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies which channel is designated as the image log..
        /// </summary>
        public static string ModifyImageLog {
            get {
                return ResourceManager.GetString("ModifyImageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies which channel is designated as the mod log..
        /// </summary>
        public static string ModifyModLog {
            get {
                return ResourceManager.GetString("ModifyModLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies a user&apos;s nickname..
        /// </summary>
        public static string ModifyNickName {
            get {
                return ResourceManager.GetString("ModifyNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds or removes roles which stay on users if they leave and rejoin the guild..
        /// </summary>
        public static string ModifyPersistentRoles {
            get {
                return ResourceManager.GetString("ModifyPersistentRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds or removes banned phrase punishments..
        /// </summary>
        public static string ModifyPunishments {
            get {
                return ResourceManager.GetString("ModifyPunishments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds the given text to a list that can be called through the SayQuote command.
        /// </summary>
        public static string ModifyQuotes {
            get {
                return ResourceManager.GetString("ModifyQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies a role color..
        /// </summary>
        public static string ModifyRoleColor {
            get {
                return ResourceManager.GetString("ModifyRoleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the hoist status of a role (whether is shows up in the user list separately)..
        /// </summary>
        public static string ModifyRoleHoist {
            get {
                return ResourceManager.GetString("ModifyRoleHoist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the mentionability status of a role..
        /// </summary>
        public static string ModifyRoleMentionability {
            get {
                return ResourceManager.GetString("ModifyRoleMentionability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies a role name..
        /// </summary>
        public static string ModifyRoleName {
            get {
                return ResourceManager.GetString("ModifyRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the permissions a role has..
        /// </summary>
        public static string ModifyRolePerms {
            get {
                return ResourceManager.GetString("ModifyRolePerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves a role..
        /// </summary>
        public static string ModifyRolePosition {
            get {
                return ResourceManager.GetString("ModifyRolePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the categories which contain rules..
        /// </summary>
        public static string ModifyRuleCategories {
            get {
                return ResourceManager.GetString("ModifyRuleCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the rules which are saved in guild settings..
        /// </summary>
        public static string ModifyRules {
            get {
                return ResourceManager.GetString("ModifyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies self assignable roles..
        /// </summary>
        public static string ModifySelfRoles {
            get {
                return ResourceManager.GetString("ModifySelfRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies which channel is designated as the server log..
        /// </summary>
        public static string ModifyServerLog {
            get {
                return ResourceManager.GetString("ModifyServerLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the channel of a webhook..
        /// </summary>
        public static string ModifyWebhookChannel {
            get {
                return ResourceManager.GetString("ModifyWebhookChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel to move the webhook to..
        /// </summary>
        public static string ModifyWebhookChannelChannel {
            get {
                return ResourceManager.GetString("ModifyWebhookChannelChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The webhook to move..
        /// </summary>
        public static string ModifyWebhookChannelWebhook {
            get {
                return ResourceManager.GetString("ModifyWebhookChannelWebhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the icon of a webhook..
        /// </summary>
        public static string ModifyWebhookIcon {
            get {
                return ResourceManager.GetString("ModifyWebhookIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A link to an image..
        /// </summary>
        public static string ModifyWebhookIconUrl {
            get {
                return ResourceManager.GetString("ModifyWebhookIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The webhook to modify the icon of..
        /// </summary>
        public static string ModifyWebhookIconWebhook {
            get {
                return ResourceManager.GetString("ModifyWebhookIconWebhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the name of a webhook..
        /// </summary>
        public static string ModifyWebhookName {
            get {
                return ResourceManager.GetString("ModifyWebhookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name to give the webhook..
        /// </summary>
        public static string ModifyWebhookNameName {
            get {
                return ResourceManager.GetString("ModifyWebhookNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The webhook to modify the name of..
        /// </summary>
        public static string ModifyWebhookNameWebhook {
            get {
                return ResourceManager.GetString("ModifyWebhookNameWebhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies a message sent when a user joins the server..
        /// </summary>
        public static string ModifyWelcomeMessage {
            get {
                return ResourceManager.GetString("ModifyWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves a user to a different voice channel..
        /// </summary>
        public static string MoveUser {
            get {
                return ResourceManager.GetString("MoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves all users in a specific channel to a different voice channel..
        /// </summary>
        public static string MoveUsers {
            get {
                return ResourceManager.GetString("MoveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents a user from typing and speaking in the guild..
        /// </summary>
        public static string Mute {
            get {
                return ResourceManager.GetString("Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets up a system protecting the guild from raiding..
        /// </summary>
        public static string PreventRaid {
            get {
                return ResourceManager.GetString("PreventRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets up a system protecting the guild from spam..
        /// </summary>
        public static string PreventSpam {
            get {
                return ResourceManager.GetString("PreventSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the rules with user specified formatting..
        /// </summary>
        public static string PrintOutRules {
            get {
                return ResourceManager.GetString("PrintOutRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes all users who have no roles and have not been seen in a specified amount of days..
        /// </summary>
        public static string PruneUsers {
            get {
                return ResourceManager.GetString("PruneUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends a message after a specified amount of time..
        /// </summary>
        public static string Remind {
            get {
                return ResourceManager.GetString("Remind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends you a reminder after the specified time..
        /// </summary>
        public static string RemindMe {
            get {
                return ResourceManager.GetString("RemindMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the nicknames of every user..
        /// </summary>
        public static string RemoveAllNickNames {
            get {
                return ResourceManager.GetString("RemoveAllNickNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the specified number of messages from a channel..
        /// </summary>
        public static string RemoveMessages {
            get {
                return ResourceManager.GetString("RemoveMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives all users who have any character in their name above a specified Utf16 limit a new nickname..
        /// </summary>
        public static string ReplaceByUtf16 {
            get {
                return ResourceManager.GetString("ReplaceByUtf16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives all users who have a specified string in their name or nickname a new nickname..
        /// </summary>
        public static string ReplaceWordsInNames {
            get {
                return ResourceManager.GetString("ReplaceWordsInNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets settings back to their default values..
        /// </summary>
        public static string ResetGuildSettings {
            get {
                return ResourceManager.GetString("ResetGuildSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarts the bot..
        /// </summary>
        public static string RestartBot {
            get {
                return ResourceManager.GetString("RestartBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the content for the given quote..
        /// </summary>
        public static string SayQuote {
            get {
                return ResourceManager.GetString("SayQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows information about the bot settings..
        /// </summary>
        public static string ShowBotSettings {
            get {
                return ResourceManager.GetString("ShowBotSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows information about guild settings..
        /// </summary>
        public static string ShowGuildSettings {
            get {
                return ResourceManager.GetString("ShowGuildSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes a user from the guild and deletes any recent messages from them..
        /// </summary>
        public static string SoftBan {
            get {
                return ResourceManager.GetString("SoftBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes everyone except admins unable to see a channel..
        /// </summary>
        public static string SoftDeleteChannel {
            get {
                return ResourceManager.GetString("SoftDeleteChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes a role then creates a role with the exact same information..
        /// </summary>
        public static string SoftDeleteRole {
            get {
                return ResourceManager.GetString("SoftDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends a message through a webhook. Use this command if you&apos;re annoying..
        /// </summary>
        public static string SpeakThroughWebhook {
            get {
                return ResourceManager.GetString("SpeakThroughWebhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text to say through the webhook..
        /// </summary>
        public static string SpeakThroughWebhookText {
            get {
                return ResourceManager.GetString("SpeakThroughWebhookText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The webhook to speak with..
        /// </summary>
        public static string SpeakThroughWebhookWebhook {
            get {
                return ResourceManager.GetString("SpeakThroughWebhookWebhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the bot is the current owner of the guild, this command will give you owner..
        /// </summary>
        public static string SwapGuildOwner {
            get {
                return ResourceManager.GetString("SwapGuildOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takes roles from a user..
        /// </summary>
        public static string TakeRole {
            get {
                return ResourceManager.GetString("TakeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mainly makes the bot say test..
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends the given guild notification in order to test it..
        /// </summary>
        public static string TestGuildNotifs {
            get {
                return ResourceManager.GetString("TestGuildNotifs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbans the user from the guild..
        /// </summary>
        public static string Unban {
            get {
                return ResourceManager.GetString("Unban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents a user from speaking in voice chat..
        /// </summary>
        public static string VoiceMute {
            get {
                return ResourceManager.GetString("VoiceMute", resourceCulture);
            }
        }
    }
}
