//To have this code auto update the version number on each build, install:
//https://marketplace.visualstudio.com/items?itemName=BennorMcCarthy.AutoT4

//The variables have to be marked static because they give errors when not

// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.

using System.Reflection;

[assembly: System.Reflection.AssemblyVersion("1.0.2850.6431")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.2850.6431")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.2850.6431")]
