// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.

using System.Reflection;

[assembly: System.Reflection.AssemblyVersionAttribute("1.1.6503.16976")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.1.6503.16976")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.1.6503.16976")]
