// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.

using System.Reflection;
using Advobot.Core;

[assembly: AssemblyVersion(Version.VersionNumber)]
[assembly: AssemblyFileVersion(Version.VersionNumber)]
[assembly: AssemblyInformationalVersion(Version.VersionNumber)]
namespace Advobot.Core
{
	internal static class Version
	{
		//To make sure every attribute has the same version number.
		public const string VersionNumber = "1.2.6504.10570";
	}
}
